// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.SettingManagement;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.SettingManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEmailSettingsAppService), typeof(EmailSettingsClientProxy))]
public partial class EmailSettingsClientProxy : ClientProxyBase<IEmailSettingsAppService>, IEmailSettingsAppService
{
    public virtual async Task<EmailSettingsDto> GetAsync()
    {
        return await RequestAsync<EmailSettingsDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(UpdateEmailSettingsDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateEmailSettingsDto), input }
        });
    }

    public virtual async Task SendTestEmailAsync(SendTestEmailInput input)
    {
        await RequestAsync(nameof(SendTestEmailAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SendTestEmailInput), input }
        });
    }
}
