// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.SettingManagement;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.SettingManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITimeZoneSettingsAppService), typeof(TimeZoneSettingsClientProxy))]
public partial class TimeZoneSettingsClientProxy : ClientProxyBase<ITimeZoneSettingsAppService>, ITimeZoneSettingsAppService
{
    public virtual async Task<string> GetAsync()
    {
        return await RequestAsync<string>(nameof(GetAsync));
    }

    public virtual async Task<List<NameValue>> GetTimezonesAsync()
    {
        return await RequestAsync<List<NameValue>>(nameof(GetTimezonesAsync));
    }

    public virtual async Task UpdateAsync(string timezone)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), timezone }
        });
    }
}
