// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Account;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.Identity;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.Account;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAccountAppService), typeof(AccountClientProxy))]
public partial class AccountClientProxy : ClientProxyBase<IAccountAppService>, IAccountAppService
{
    public virtual async Task<IdentityUserDto> RegisterAsync(RegisterDto input)
    {
        return await RequestAsync<IdentityUserDto>(nameof(RegisterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RegisterDto), input }
        });
    }

    public virtual async Task SendPasswordResetCodeAsync(SendPasswordResetCodeDto input)
    {
        await RequestAsync(nameof(SendPasswordResetCodeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SendPasswordResetCodeDto), input }
        });
    }

    public virtual async Task<bool> VerifyPasswordResetTokenAsync(VerifyPasswordResetTokenInput input)
    {
        return await RequestAsync<bool>(nameof(VerifyPasswordResetTokenAsync), new ClientProxyRequestTypeValue
        {
            { typeof(VerifyPasswordResetTokenInput), input }
        });
    }

    public virtual async Task ResetPasswordAsync(ResetPasswordDto input)
    {
        await RequestAsync(nameof(ResetPasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResetPasswordDto), input }
        });
    }
}
