namespace SmartSoftware.FeatureManagement.EntityFrameworkCore;

public class FeatureManagementStore_Tests : FeatureManagementStore_Tests<SmartSoftwareFeatureManagementEntityFrameworkCoreTestModule>
{

}
