namespace SmartSoftware.FeatureManagement.EntityFrameworkCore;

public class FeatureValueRepositoryTests : FeatureValueRepository_Tests<SmartSoftwareFeatureManagementEntityFrameworkCoreTestModule>
{

}
