// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Admin.Menus;
using SmartSoftware.CmsKit.Menus;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Admin.Menus;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMenuItemAdminAppService), typeof(MenuItemAdminClientProxy))]
public partial class MenuItemAdminClientProxy : ClientProxyBase<IMenuItemAdminAppService>, IMenuItemAdminAppService
{
    public virtual async Task<ListResultDto<MenuItemDto>> GetListAsync()
    {
        return await RequestAsync<ListResultDto<MenuItemDto>>(nameof(GetListAsync));
    }

    public virtual async Task<MenuItemWithDetailsDto> GetAsync(Guid id)
    {
        return await RequestAsync<MenuItemWithDetailsDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MenuItemDto> CreateAsync(MenuItemCreateInput input)
    {
        return await RequestAsync<MenuItemDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MenuItemCreateInput), input }
        });
    }

    public virtual async Task<MenuItemDto> UpdateAsync(Guid id, MenuItemUpdateInput input)
    {
        return await RequestAsync<MenuItemDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MenuItemUpdateInput), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task MoveMenuItemAsync(Guid id, MenuItemMoveInput input)
    {
        await RequestAsync(nameof(MoveMenuItemAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MenuItemMoveInput), input }
        });
    }

    public virtual async Task<PagedResultDto<PageLookupDto>> GetPageLookupAsync(PageLookupInputDto input)
    {
        return await RequestAsync<PagedResultDto<PageLookupDto>>(nameof(GetPageLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PageLookupInputDto), input }
        });
    }
}
