// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Admin.Tags;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Admin.Tags;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEntityTagAdminAppService), typeof(EntityTagAdminClientProxy))]
public partial class EntityTagAdminClientProxy : ClientProxyBase<IEntityTagAdminAppService>, IEntityTagAdminAppService
{
    public virtual async Task AddTagToEntityAsync(EntityTagCreateDto input)
    {
        await RequestAsync(nameof(AddTagToEntityAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EntityTagCreateDto), input }
        });
    }

    public virtual async Task RemoveTagFromEntityAsync(EntityTagRemoveDto input)
    {
        await RequestAsync(nameof(RemoveTagFromEntityAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EntityTagRemoveDto), input }
        });
    }

    public virtual async Task SetEntityTagsAsync(EntityTagSetDto input)
    {
        await RequestAsync(nameof(SetEntityTagsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EntityTagSetDto), input }
        });
    }
}
