// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Contents;
using SmartSoftware.CmsKit.Public.Pages;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Public.Pages;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPagePublicAppService), typeof(PagesPublicClientProxy))]
public partial class PagesPublicClientProxy : ClientProxyBase<IPagePublicAppService>, IPagePublicAppService
{
    public virtual async Task<PageDto> FindBySlugAsync(string slug)
    {
        return await RequestAsync<PageDto>(nameof(FindBySlugAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), slug }
        });
    }

    public virtual async Task<PageDto> FindDefaultHomePageAsync()
    {
        return await RequestAsync<PageDto>(nameof(FindDefaultHomePageAsync));
    }

    public virtual async Task<bool> DoesSlugExistAsync(string slug)
    {
        return await RequestAsync<bool>(nameof(DoesSlugExistAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), slug }
        });
    }
}
