// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Tags;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Public.Tags;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITagAppService), typeof(TagPublicClientProxy))]
public partial class TagPublicClientProxy : ClientProxyBase<ITagAppService>, ITagAppService
{
    public virtual async Task<List<TagDto>> GetAllRelatedTagsAsync(string entityType, string entityId)
    {
        return await RequestAsync<List<TagDto>>(nameof(GetAllRelatedTagsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType },
            { typeof(string), entityId }
        });
    }

    public virtual async Task<List<PopularTagDto>> GetPopularTagsAsync(string entityType, int maxCount)
    {
        return await RequestAsync<List<PopularTagDto>>(nameof(GetPopularTagsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), entityType },
            { typeof(int), maxCount }
        });
    }
}
