namespace SmartSoftware.PermissionManagement.EntityFrameworkCore;

public class EFCorePermissionDefinitionRecordRepository_Tests : PermissionDefinitionRecordRepository_Tests<SmartSoftwarePermissionManagementEntityFrameworkCoreTestModule>
{

}
