namespace SmartSoftware.BlobStoring.Database.EntityFrameworkCore;

public abstract class BlobStoringDatabaseEntityFrameworkCoreTestBase : BlobStoringDatabaseTestBase<BlobStoringDatabaseEntityFrameworkCoreTestModule>
{

}
