using SmartSoftware.DependencyInjection;

namespace SmartSoftware.MemoryDb.DependencyInjection;

public interface ISmartSoftwareMemoryDbContextRegistrationOptionsBuilder : ISmartSoftwareCommonDbContextRegistrationOptionsBuilder
{

}
