using SmartSoftware.DependencyInjection;

namespace SmartSoftware.MongoDB.DependencyInjection;

public interface ISmartSoftwareMongoDbContextRegistrationOptionsBuilder : ISmartSoftwareCommonDbContextRegistrationOptionsBuilder
{

}
