// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.FeatureManagement;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.FeatureManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFeatureAppService), typeof(FeaturesClientProxy))]
public partial class FeaturesClientProxy : ClientProxyBase<IFeatureAppService>, IFeatureAppService
{
    public virtual async Task<GetFeatureListResultDto> GetAsync(string providerName, string providerKey)
    {
        return await RequestAsync<GetFeatureListResultDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), providerName },
            { typeof(string), providerKey }
        });
    }

    public virtual async Task UpdateAsync(string providerName, string providerKey, UpdateFeaturesDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), providerName },
            { typeof(string), providerKey },
            { typeof(UpdateFeaturesDto), input }
        });
    }

    public virtual async Task DeleteAsync(string providerName, string providerKey)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), providerName },
            { typeof(string), providerKey }
        });
    }
}
