// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.Docs.Documents;
using SmartSoftware.Docs.Projects;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.Docs.Projects;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProjectAppService), typeof(DocsProjectClientProxy))]
public partial class DocsProjectClientProxy : ClientProxyBase<IProjectAppService>, IProjectAppService
{
    public virtual async Task<ListResultDto<ProjectDto>> GetListAsync()
    {
        return await RequestAsync<ListResultDto<ProjectDto>>(nameof(GetListAsync));
    }

    public virtual async Task<ProjectDto> GetAsync(string shortName)
    {
        return await RequestAsync<ProjectDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName }
        });
    }

    public virtual async Task<string> GetDefaultLanguageCodeAsync(string shortName, string version)
    {
        return await RequestAsync<string>(nameof(GetDefaultLanguageCodeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName },
            { typeof(string), version }
        });
    }

    public virtual async Task<ListResultDto<VersionInfoDto>> GetVersionsAsync(string shortName)
    {
        return await RequestAsync<ListResultDto<VersionInfoDto>>(nameof(GetVersionsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName }
        });
    }

    public virtual async Task<LanguageConfig> GetLanguageListAsync(string shortName, string version)
    {
        return await RequestAsync<LanguageConfig>(nameof(GetLanguageListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName },
            { typeof(string), version }
        });
    }
}
