// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using SmartSoftware.Application.Dtos;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Modeling;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.AspNetCore.Mvc.MultiTenancy;

// ReSharper disable once CheckNamespace
namespace Pages.SmartSoftware.MultiTenancy.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISmartSoftwareTenantAppService), typeof(SmartSoftwareTenantClientProxy))]
public partial class SmartSoftwareTenantClientProxy : ClientProxyBase<ISmartSoftwareTenantAppService>, ISmartSoftwareTenantAppService
{
    public virtual async Task<FindTenantResultDto> FindTenantByNameAsync(string name)
    {
        return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<FindTenantResultDto> FindTenantByIdAsync(Guid id)
    {
        return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
