// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using SmartSoftware.Application.Dtos;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Modeling;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.AspNetCore.Mvc.ApplicationConfigurations;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.AspNetCore.Mvc.ApplicationConfigurations.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISmartSoftwareApplicationLocalizationAppService), typeof(SmartSoftwareApplicationLocalizationClientProxy))]
public partial class SmartSoftwareApplicationLocalizationClientProxy : ClientProxyBase<ISmartSoftwareApplicationLocalizationAppService>, ISmartSoftwareApplicationLocalizationAppService
{
    public virtual async Task<ApplicationLocalizationDto> GetAsync(ApplicationLocalizationRequestDto input)
    {
        return await RequestAsync<ApplicationLocalizationDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ApplicationLocalizationRequestDto), input }
        });
    }
}
