// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.Blogging.Blogs;
using SmartSoftware.Blogging.Blogs.Dtos;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.Blogging;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBlogAppService), typeof(BlogsClientProxy))]
public partial class BlogsClientProxy : ClientProxyBase<IBlogAppService>, IBlogAppService
{
    public virtual async Task<ListResultDto<BlogDto>> GetListAsync()
    {
        return await RequestAsync<ListResultDto<BlogDto>>(nameof(GetListAsync));
    }

    public virtual async Task<BlogDto> GetByShortNameAsync(string shortName)
    {
        return await RequestAsync<BlogDto>(nameof(GetByShortNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), shortName }
        });
    }

    public virtual async Task<BlogDto> GetAsync(Guid id)
    {
        return await RequestAsync<BlogDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
