// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Admin.GlobalResources;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Admin.GlobalResources;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGlobalResourceAdminAppService), typeof(GlobalResourceAdminClientProxy))]
public partial class GlobalResourceAdminClientProxy : ClientProxyBase<IGlobalResourceAdminAppService>, IGlobalResourceAdminAppService
{
    public virtual async Task<GlobalResourcesDto> GetAsync()
    {
        return await RequestAsync<GlobalResourcesDto>(nameof(GetAsync));
    }

    public virtual async Task SetGlobalResourcesAsync(GlobalResourcesUpdateDto input)
    {
        await RequestAsync(nameof(SetGlobalResourcesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GlobalResourcesUpdateDto), input }
        });
    }
}
