// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Blogs;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Blogs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBlogFeatureAppService), typeof(BlogFeatureClientProxy))]
public partial class BlogFeatureClientProxy : ClientProxyBase<IBlogFeatureAppService>, IBlogFeatureAppService
{
    public virtual async Task<BlogFeatureDto> GetOrDefaultAsync(Guid blogId, string featureName)
    {
        return await RequestAsync<BlogFeatureDto>(nameof(GetOrDefaultAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), blogId },
            { typeof(string), featureName }
        });
    }
}
