// This file is automatically generated by SS framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SmartSoftware;
using SmartSoftware.Application.Dtos;
using SmartSoftware.DependencyInjection;
using SmartSoftware.Http.Client;
using SmartSoftware.Http.Client.ClientProxying;
using SmartSoftware.Http.Modeling;
using SmartSoftware.CmsKit.Public.GlobalResources;

// ReSharper disable once CheckNamespace
namespace SmartSoftware.CmsKit.Public.GlobalResources;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGlobalResourcePublicAppService), typeof(GlobalResourcePublicClientProxy))]
public partial class GlobalResourcePublicClientProxy : ClientProxyBase<IGlobalResourcePublicAppService>, IGlobalResourcePublicAppService
{
    public virtual async Task<GlobalResourceDto> GetGlobalScriptAsync()
    {
        return await RequestAsync<GlobalResourceDto>(nameof(GetGlobalScriptAsync));
    }

    public virtual async Task<GlobalResourceDto> GetGlobalStyleAsync()
    {
        return await RequestAsync<GlobalResourceDto>(nameof(GetGlobalStyleAsync));
    }
}
